# Installation process of HA Core
# Based on official guide on https://www.home-assistant.io/installation/linux#install-home-assistant-core

- name: Prepare HA Core Dependencies and User
  hosts: ha_server
  become: true
  tasks:
    - name: Ensure HA Core Dependencies
      register: deps_out
      ansible.builtin.apt:
        state: present
        pkg:
          - python3
          - python3-dev
          - python3-venv
          - python3-pip
          - bluez
          - libffi-dev
          - libssl-dev
          - libjpeg-dev
          - zlib1g-dev
          - autoconf
          - build-essential
          - libopenjp2-7
          - libtiff6
          - libturbojpeg0-dev
          - tzdata
          - ffmpeg
          - liblapack3
          - liblapack-dev
          - libatlas-base-dev

    - name: Ensure Home Assistant User
      ansible.builtin.user:
        name: homeassistant
        system: true
        create_home: true

    - name: Ensure HA Config Folder
      ansible.builtin.file:
        path: /srv/homeassistant
        state: directory
        mode: "u=rwx,g=rwx,o=r"
        owner: homeassistant
        group: homeassistant
        recurse: true

- name: Install Home Assistant Core
  hosts: ha_server
  become: true
  tasks:
    - name: Install Home Assistant Core
      ansible.builtin.pip:
        state: present
        name: homeassistant
        version: "2024.12.2"
        virtualenv: /srv/homeassistant
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Ensure HA Systemd Service File
      ansible.builtin.template:
        src: home-assistant.service.j2
        dest: "/etc/systemd/system/home-assistant.service"
        owner: root
        group: root
        mode: "0644"

    - name: Ensure HA Service Started and Enabled
      ansible.builtin.systemd:
        name: home-assistant
        daemon_reload: true
        enabled: true
        state: started

    - name: Allow ports used by HA Web
      community.general.ufw:
        rule: allow
        port: 8123
        proto: tcp
        # Remove or add other subnet if remote access is allowed
        src: "{{ item }}"
      loop:
        - 192.168.18.0/16
